name: eduinfo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
